// app/layout.jsx
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/redux/Providers";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { GlobalProvider } from "./context/GlobalState";
import { Inter } from 'next/font/google';
import Header from "@/components/Header";
import { Toaster } from "sonner";

// Load Inter font for primary text
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

// Load local Geist font for accents and headings
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} font-sans antialiased relative bg-white`}
      >
        <GlobalProvider>
          <Providers>
            <Header />
            <Toaster />
            <div>
              <Sidebar />
              {children}
            </div>
            <Footer />
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  );
}